
function noise_verification(L)

    reverse_eng = [ ...
        512 225; ...
        573 237; ...
        651 252; ...
        825 333; ...
        572 423; ...
        583 408; ...
        736 415; ...
        413 281; ...
        327 349; ...
        425 369; ...
        375 497; ...
        500 497; ...
        360 636; ...
        476 606; ...
        541 614; ...
        651 650; ...
        742 567; ...
        561 768; ...
        608 870];
    reverse_eng = reverse_eng - reverse_eng(12, :);
    reverse_eng = reverse_eng * [1 0; 0 -1] / 5;
    num_ell = size(reverse_eng, 1);
    Lab_set = [L*ones(num_ell, 1), reverse_eng];
    XYZ_set = Lab2XYZ(Lab_set);
    % XYZ_set = get_sample_L(num_ell, L);
    % Lab_set = XYZ2Lab(XYZ_set);
    local_size = 1000;
    max_n = 5000 * [1 1 1];
    XYZ = simulate_camera_noise(max_n, local_size, num_ell, XYZ_set);
    XYZ = reshape(XYZ, [local_size * num_ell, 3]);
    Lab = XYZ2Lab(XYZ);
    Lab = reshape(Lab, [num_ell, local_size, 3]);
    CS = color_spaces_collection('CIELAB', RECORD);
    AO = CS.axis_Lab_order;
    angle = 2*pi*(0:0.01:1.01)';
    x = [cos(angle); 0];
    y = [sin(angle); 0];
%     figure;
%     hold on;
    for ell = 1:num_ell
        Cov = get_covariance(squeeze(Lab(ell,:,:)));
        Cov = Cov(2:3, 2:3);
        [U,S,~] = svd(Cov);
    %     U * S * V' - Cov
        M = U * S.^(1/2);
    %     M * M' - Cov
    %     M = M^(-1);
        L = L + 1;  % !!!!!!! Crutch for visibility!!!
        C = [x y] * M' + Lab_set(ell, 2:3);
        C = [L*ones(size(C,1),1), C];
        plot3(C(end, abs(AO(1))), C(end, abs(AO(2))), C(end, abs(AO(3))), 's', 'MarkerSize', 4, 'color', [0 0 0]);
        plot3(C(1:end-1, abs(AO(1))), C(1:end-1, abs(AO(2))), C(1:end-1, abs(AO(3))), 'LineWidth', 1, 'color', [1 1 1]);
    end
end