
function XYZ_sRGB_planes = get_XYZ_sRGB_planes()
    XYZ_sRGB_vertex = (linRGB_matrix^(-1)*vertex')';
    idx = [1 2 3; ...
           1 3 4; ...
           1 4 2; ...
           6 5 8; ...
           7 6 8; ...
           5 7 8];
    XYZ_sRGB_planes = zeros(6, 4);
    for i = 1:6
        normal = cross( ...
            XYZ_sRGB_vertex(idx(i, 2), :) - XYZ_sRGB_vertex(idx(i, 1), :), ...
            XYZ_sRGB_vertex(idx(i, 3), :) - XYZ_sRGB_vertex(idx(i, 1), :));
        const = - normal * XYZ_sRGB_vertex(idx(i, 1), :)';
        XYZ_sRGB_planes(i, :) = - [normal, const];
    end
end

